"""Initial schema: tenants, members, events, tasks, stamps, rewards, audit —
plus PostGIS, RLS policies, and the RLS-restricted runtime app role.

Revision ID: 0001
"""

import os

from alembic import op
import sqlalchemy as sa

from app.db.rls import all_rls_sql
from app.models import Base

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    bind = op.get_bind()

    # Extensions: PostGIS for GPS radius checks (spec §5.8), pgcrypto for UUIDs.
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")

    # Initial schema straight from the models (single source of truth for rev 1;
    # subsequent revisions use explicit autogenerated DDL).
    Base.metadata.create_all(bind=bind)

    # Row-Level Security + runtime app role (spec §4.2, §5.7).
    app_role_password = os.environ.get("APP_DB_PASSWORD", "zoustec_app_password")
    for statement in all_rls_sql(app_role_password):
        op.execute(statement)


def downgrade() -> None:
    Base.metadata.drop_all(bind=op.get_bind())
